site_name: ReDU Documentation
nav:
    - ReDU Introduction: index.md
    - How to Contribute: HowtoContribute.md
    - Analyze Your Data:
        - Multivariate - Project Your Data: AnalyzeYourData_MultivariateComparisons.md
        - Co-Analysis at GNPS: 
            - Molecular Networking at GNPS: AnalyzeYourData_GNPS_MolecularNetworking.md
            - Library Search at GNPS: AnalyzeYourData_GNPS_LibrarySearch.md
            - Selected File PCA: SelectedPCA.md
    - Analyze Public Data:
        - Multivariate - Explore Public Data: AnalyzePublicData_MultivariateComparisons.md
        - Chemical Explorer: AnalyzePublicData_ChemicalExplorerSampleInformationAssociation.md
        - Re-analysis at GNPS: 
            - Molecular Networking at GNPS: AnalyzePublicData_GNPS_MolecularNetworking.md
            - Library Search at GNPS: AnalyzePublicData_GNPS_LibrarySearch.md
            - Chemical Explorer Analysis: AnalyzePublicData_ChemicalExplorer.md
            - Group Comparator: AnalyzePublicData_GroupComparator.md
            - Selected File PCA: SelectedPCA.md
    - Contact: contact.md
    - FAQ: FAQ.md
theme:
    name: material
    #name: readthedocs

    #palette:
    #    primary: 'light blue'
    #    accent: 'orange'
    #font:
    #    text: 'Roboto'
    #    code: 'Roboto Mono'

    #logo: 'img/GNPS_logo.jpg'
#theme: readthedocs
#theme:
#  name: 'rtd-dropdown'
google_analytics: ['UA-8412213-5', 'ccms-ucsd.github.io']
