site_name: ReDU Documentation
site_url: https://mwang87.github.io/ReDU-MS2-Documentation/
edit_uri: https://github.com/mwang87/ReDU-MS2-Documentation/blob/master/docs/
repo_name: mwang87/ReDU-MS2-Documentation
repo_url: https://github.com/mwang87/ReDU-MS2-Documentation

nav:
    - ReDU Introduction: index.md
    - How to Contribute: HowtoContribute.md
    - Multivariate Analysis (PCA) of ReDU Data: multivariate_analysis.md
    - Analyze Your Data:
        - Co-Analysis at GNPS: 
            - Molecular Networking at GNPS: AnalyzeYourData_GNPS_MolecularNetworking.md
            - Library Search at GNPS: AnalyzeYourData_GNPS_LibrarySearch.md
            - Selected File PCA: AnalyzeYourData_SelectedPCA.md
    - Analyze Public Data:
        - Chemical Explorer: AnalyzePublicData_ChemicalExplorerSampleInformationAssociation.md
        - Re-analysis at GNPS: 
            - Molecular Networking at GNPS: AnalyzePublicData_GNPS_MolecularNetworking.md
            - Library Search at GNPS: AnalyzePublicData_GNPS_LibrarySearch.md
            - Chemical Explorer: AnalyzePublicData_ChemicalExplorer.md
            - Group Comparator: AnalyzePublicData_GroupComparator.md
            - Selected File PCA: AnalyzePublicData_SelectedPCA.md
    - Contact: contact.md
    - FAQ: FAQ.md
theme:
    name: material

plugins:
    - search
    - git-revision-date-localized:
        type: datetime

markdown_extensions:
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    
google_analytics: ['UA-8412213-5', 'ccms-ucsd.github.io']
