site_name: ReDU Documentation
edit_uri: https://github.com/mwang87/ReDU-MS2-Documentation/blob/master/docs/
nav:
    - ReDU Introduction: index.md
    - How to Contribute: HowtoContribute.md
    - Analyze Your Data:
        - Multivariate - Project Your Data: AnalyzeYourData_MultivariateComparisons.md
        - Co-Analysis at GNPS: 
            - Molecular Networking at GNPS: AnalyzeYourData_GNPS_MolecularNetworking.md
            - Library Search at GNPS: AnalyzeYourData_GNPS_LibrarySearch.md
            - Selected File PCA: AnalyzeYourData_SelectedPCA.md
    - Analyze Public Data:
        - Multivariate - Explore Public Data: AnalyzePublicData_MultivariateComparisons.md
        - Chemical Explorer: AnalyzePublicData_ChemicalExplorerSampleInformationAssociation.md
        - Re-analysis at GNPS: 
            - Molecular Networking at GNPS: AnalyzePublicData_GNPS_MolecularNetworking.md
            - Library Search at GNPS: AnalyzePublicData_GNPS_LibrarySearch.md
            - Chemical Explorer: AnalyzePublicData_ChemicalExplorer.md
            - Group Comparator: AnalyzePublicData_GroupComparator.md
            - Selected File PCA: AnalyzePublicData_SelectedPCA.md
    - Contact: contact.md
    - FAQ: FAQ.md
theme:
    name: material

plugins:
    - search
    - git-revision-date

markdown_extensions:
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    
google_analytics: ['UA-8412213-5', 'ccms-ucsd.github.io']
